version: '3.1'

services:

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: StrongPassord!123
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db  # <-- persistent volume

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: StrongPassord!123
      ME_CONFIG_MONGODB_URL: mongodb://root:StrongPassord!123@mongo:27017/
      ME_CONFIG_BASICAUTH: True
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: StrongPassord!123
    depends_on:
      - mongo

volumes:
  mongo-data: